name : Test Action
on: [push]

jobs:
  get-num-square:
  runs-on: ubntu-latest
  name: Returns the number square
  steps:
    - name: Checkout
      uses: action/checkout@v2
    - name: fetch num squared
      id: get square
      uses: ./
      with:
        num: 11
      name: print the square
        run: echo "${{ steps.get_square.outputs.num.squared }}"
